theme: minima  # 使用本地安装的 Minima 主题

# _config.yml
# remote_theme: jekyll/minima@v3.0.0  # 注意添加 'v' 前缀

# 站点基本信息
title: "macRong's blog"         # 显示在浏览器标签和首页顶部
email: d8tv@163.com       # 联系邮箱（会显示在页脚）
description: "个人开发搞钱"  # 简短描述
baseurl: ""                 # 子路径（如博客部署在域名下的子目录，填 "/blog"）
url: "http://gxxn.com"  # 博客完整域名（必填）

# 作者信息（会显示在文章底部或 About 页）
author:
  name: Colin
#   bio: 技术开发等

# 导航菜单（顶部导航栏显示的页面）
header_pages:
  - product.md       
  - archive.md      # 归档页（需手动创建）
  - about.md        # 关于页

# 分页设置（首页每页显示的文章数量）
paginate: 0         # 每页5篇文章

# Minima 主题特有配置
minima:
  cover_image: /assets/images/default-cover.jpg  # 文章默认封面图路径
  skin: classic     # 主题皮肤（可选：classic/default、dark、solarized-light）https://jekyll.github.io/minima/


social_links:
  - { platform: Github, user_url: "https://github.com/macRong" }  # 首字母大写
  - { platform: Twitter, user_url: "https://twitter.com/colinluckyrong" }  # 首字母大写
  - { platform: Rss, user_url: "https://macrong.github.io/feed.xml" }  # 首字母大写


# 启用的插件（GitHub Pages 已内置支持）
plugins:
  - jekyll-paginate   # 分页功能
  - jekyll-seo-tag    # 自动生成SEO标签（标题、描述等）
  - jekyll-feed       # 生成RSS订阅源

# _config.yml
show_excerpts: true  # 显示摘要（默认 false）