name: Deploy Jekyll Site

on:
  push:
    branches: [ main ]  # 监听 main 分支的推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 设置 Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # 匹配你的 Ruby 版本
          bundler-cache: true  # 缓存依赖

      - name: 构建 Jekyll 站点
        run: bundle exec jekyll build  # 生成静态文件到 _site 目录

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # 部署 _site 目录下的内容